name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: clojure:latest
    steps:
    - uses: actions/checkout@v1
    - name: CI
      run: lein with-profile dev trampoline test && lein uberjar
      env:
        FEEDS2IMAP_HOME: /tmp/
        LEIN_JVM_OPTS: "-Xms512m -Xmx2024m"
        NUM_TESTS: 30
